### ISSUE TITLE
Decide which (human) languages need to be supported for NLQ

### ISSUE THREAD

**Issue by robknapen** [soilwise-he/natural-language-querying#13]
LLMs vary in the amount of multilingual training data that has been used. Also, creating semantic embeddings is not the same for every language. Therefore it is import to decide early the scope of human languages that need to be supported.

**Comment by BerkvensNick** [comment]
@robknapen We do not have this requirement yet and I think we will only get it during the evaluation at the end of the first iteration with the UC and JRC. The EUSO dashboard website is in English (https://esdac.jrc.ec.europa.eu/esdacviewer/euso-dashboard/) implying JRC (ESDAC) currently 'serves' their users in English. Can we currently focus on English (knowing it is realistic that later in the process JRC will inquire if they can serve their users in the national language, but maybe we can evaluate our choices when that question comes),  and when having to make choices go for the most multilingual LLM and embeddings-algorithm.

**Comment by robknapen** [comment]
Sure we can. Sounds like a good approach to focus on using multi-lingual embedding and language models, even though most will be in English first.

**Comment by robknapen** [comment]
Closed as answered.
