### ISSUE TITLE
Define connection between the NLQ component and the Graph Database

### ISSUE THREAD

**Issue by robknapen** [soilwise-he/natural-language-querying#7]

**Comment by robknapen** [comment]
According to the (Brugge) architecture the sole connection between the NLQ component and the triple store is the SPARQL API. So we can try to have the LLM generate proper SPARQL queries (might need few shot examples in the prompt) or use fixed queries via tool calling (might be more reliable, but less flexible).

**Comment by BerkvensNick** [comment]
I agree
