### ISSUE TITLE
Discuss adding guardrails to safeguard LLM usage

### ISSUE THREAD

**Issue by robknapen** [soilwise-he/natural-language-querying#9]
LLMs with public access typically require guardrails to prevent misuse and hacking. Guardrails will try to keep generated output safe and responsible, in accordance with SoilWise standards.

**Comment by BerkvensNick** [comment]
do you have any examples of guardrails that can be implemented? A first "safety" could be to put this behind a "authorization" layer to which users with an account have access to?

**Comment by BerkvensNick** [comment]
Do you have any examples of guardrails that can be implemented? 

A first "safety" could be to put this behind a "authorization" layer to which users with an account have access to?

**Comment by BerkvensNick** [comment]
do you have any examples of guardrails that can be implemented? A first "safety" could be to put this behind a "authorization" layer to which users with an account have access to?

**Comment by robknapen** [comment]
Think of things like “Don’t generate text with profanities”, or “Don’t generate text that is off topic”. This Hub has many examples that might indicate what to consider: https://hub.guardrailsai.com/

Authorisation and e.g. rate-limiting are more to control access and usage of a (LLM) service, not about what kind of text the model is allowed to generate.

**Comment by BerkvensNick** [comment]
thanks for the clarification Rob! Also a very nice resource for the guardrails!!  If I understand correctly, we can also use this code and integrate when we want to set this up?

**Comment by robknapen** [comment]
I don't know that. It was just some examples that I could easily find. They seem to want to share guardrails publicly, when using the OSS package. There are pros and cons to that of course. Guardrails are usually what a hacker will be trying to circumvent first. But initially it might be sufficient. We can try it, or search for something similar.

**Comment by robknapen** [comment]
Closing for now. Issue might turn up again based on the work on the user cases and resulting requirements for any user facing UI / LLM deployments.
